package AlgorithmsTest

import algo.AlgoBridges
import java.util.stream.Stream
import kotlin.random.Random
import kotlin.test.Test
import kotlin.test.assertEquals
import model.Graph
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource

class FindBridgesTest {
    companion object {

        @JvmStatic
        fun graphGenerator(): Stream<Arguments> {
            return Stream.generate {
                    val bridges = ArrayDeque<Pair<Long, Long>>()

                    val components = ArrayDeque<Set<Int>>()

                    val calculateEdgeId = { firstVertexId: Int, secondVertexId: Int ->
                        firstVertexId * 100000 + secondVertexId
                    }

                    val graph = Graph()
                    val countOfComponents = Random.Default.nextInt(2, 10)
                    for (i in 0..<countOfComponents) {
                        val countNodesInComponent = Random.Default.nextInt(1, 20)
                        val firstId = i * 1000
                        val lastId = i * 1000 + countNodesInComponent
                        if (countNodesInComponent == 2) {
                            bridges.add(firstId.toLong() to lastId.toLong() - 1)
                        }
                        val component = mutableSetOf<Int>()
                        for (j in 0..<countNodesInComponent) {
                            var id = Random.Default.nextInt(firstId, lastId)
                            while (component.contains(id)) {
                                id = Random.Default.nextInt(firstId, lastId)
                            }
                            graph.addVertex(id.toLong(), "")
                            component.add(id)
                        }
                        component.forEach { firstVertex ->
                            component.forEach { secondVertex ->
                                if (firstVertex != secondVertex) {
                                    graph.addEdge(
                                        firstVertex.toLong(),
                                        secondVertex.toLong(),
                                        "",
                                        calculateEdgeId(firstVertex, secondVertex).toLong(),
                                    )
                                }
                            }
                        }
                        components.add(component)
                    }
                    for (i in 0..components.size - 2) {
                        val firstVertex = components[i].random()
                        val secondVertex = components[i + 1].random()
                        graph.addEdge(
                            firstVertex.toLong(),
                            secondVertex.toLong(),
                            "",
                            calculateEdgeId(firstVertex, secondVertex).toLong(),
                        )
                        bridges.add(Pair(firstVertex.toLong(), secondVertex.toLong()))
                    }
                    Arguments.of(graph, bridges)
                }
                .limit(1000)
        }
    }

    /**
     * test accepts a randomly generated graph, all bridges are calculated during generation. when
     * creating a graph, a certain number of connectivity components are generated and 1 edge is
     * laid between them. the test checks the correctness of the bridges generated by the algorithm.
     */
    @ParameterizedTest(name = "test for findBridges")
    @MethodSource("graphGenerator")
    fun `check for random graph`(graph: Graph, correctBridges: ArrayDeque<Pair<Long, Long>>) {
        val algoBridges = AlgoBridges(graph)
        algoBridges.findBridges()
        val bridges = algoBridges.bridges

        assertEquals(correctBridges.size, bridges.size)

        for (i in bridges) {
            assertEquals(
                correctBridges.contains(i) || correctBridges.contains(Pair(i.second, i.first)),
                true,
            )
        }
    }

    /** Test finds bridges in graph with one node */
    @Test
    fun `graph with one node`() {
        val graph = Graph(false, true)
        graph.addVertex(1, "A")

        val algoBridges = AlgoBridges(graph)
        algoBridges.findBridges()

        assertEquals(0, algoBridges.bridges.size)
    }

    /** Test finds bridges : A ── B in graph with two node */
    @Test
    fun `graph with two node`() {
        val graph = Graph(false, true)
        graph.addVertex(1, "A")
        graph.addVertex(2, "B")
        graph.addEdge(1, 2, "A <-> B", 3, 3F)

        val algoBridges = AlgoBridges(graph)
        algoBridges.findBridges()

        assertEquals(1, algoBridges.bridges.size)
        assert(
            (algoBridges.bridges[0].first == 1L && algoBridges.bridges[0].second == 2L) ||
                (algoBridges.bridges[0].first == 2L && algoBridges.bridges[0].second == 1L)
        )
    }

    /**
     *     A     Test finds bridges in graph with cycle
     *    / \
     *   /   \
     *  /     \
     *
     * B ----- C
     */
    @Test
    fun `graph with cycle`() {
        val graph = Graph(false, true)
        graph.addVertex(1, "A")
        graph.addVertex(2, "B")
        graph.addVertex(3, "C")
        graph.addEdge(1, 2, "A <-> B", 4, 3F)
        graph.addEdge(1, 3, "A <-> C", 5, 3F)
        graph.addEdge(2, 3, "B <-> C", 6, 3F)

        val algoBridges = AlgoBridges(graph)
        algoBridges.findBridges()

        assertEquals(0, algoBridges.bridges.size)
    }

    /**
     *     A     Test finds bridges in tree
     *    /
     *   B -- C -- D
     */
    @Test
    fun `graph is tree`() {
        val correctBridges = ArrayDeque<Pair<Long, Long>>()
        correctBridges.add(Pair(1, 2))
        correctBridges.add(Pair(2, 3))
        correctBridges.add(Pair(3, 4))

        val graph = Graph(false, true)
        graph.addVertex(1, "A")
        graph.addVertex(2, "B")
        graph.addVertex(3, "C")
        graph.addVertex(4, "D")
        graph.addEdge(1, 2, "A <-> B", 5, 3F)
        graph.addEdge(2, 3, "B <-> C", 6, 3F)
        graph.addEdge(3, 4, "C <-> D", 7, 3F)

        val algoBridges = AlgoBridges(graph)
        algoBridges.findBridges()

        assertEquals(3, algoBridges.bridges.size)

        for (i in algoBridges.bridges) {
            assertEquals(
                correctBridges.contains(i) || correctBridges.contains(Pair(i.second, i.first)),
                true,
            )
        }
    }

    /**
     *     C        A   Test finds bridges in graph with two components:
     *   /   \      |   cycle and two nodes
     *  /     \     |
     *
     * E ----- D B
     */
    @Test
    fun `graph with several components`() {
        val graph = Graph(false, true)
        graph.addVertex(0, "A")
        graph.addVertex(1, "B")
        graph.addVertex(2, "C")
        graph.addVertex(3, "D")
        graph.addVertex(4, "E")
        graph.addVertex(5, "G")
        graph.addEdge(0, 1, "A <-> B", 6, 3F)
        graph.addEdge(2, 3, "C <-> D", 7, 3F)
        graph.addEdge(3, 4, "D <-> E", 8, 3F)
        graph.addEdge(2, 4, "C <-> E", 8, 3F)

        val algoBridges = AlgoBridges(graph)
        algoBridges.findBridges()

        assertEquals(1, algoBridges.bridges.size)
        assert(
            (algoBridges.bridges[0].first == 0L && algoBridges.bridges[0].second == 1L) ||
                (algoBridges.bridges[0].first == 1L && algoBridges.bridges[0].second == 0L)
        )
    }

    /**
     *       A ------ B    Test finds bridges in graph with two cycles and two bridges
     *       |        |
     *       |        |
     *       F        C -- D -- E
     *      | \      /
     *      |  \    /
     *      |   \  /
     *      G -- H
     */
    @Test
    fun `graph with cycles and bridges`() {
        val correctBridges = ArrayDeque<Pair<Long, Long>>()
        correctBridges.add(Pair(2, 3))
        correctBridges.add(Pair(3, 4))

        val graph = Graph(false, true)
        graph.addVertex(0, "A")
        graph.addVertex(1, "B")
        graph.addVertex(2, "C")
        graph.addVertex(3, "D")
        graph.addVertex(4, "E")
        graph.addVertex(5, "F")
        graph.addVertex(6, "G")
        graph.addVertex(7, "H")
        graph.addEdge(5, 6, "F <-> G", 8, 3F)
        graph.addEdge(6, 7, "G <-> H", 9, 3F)
        graph.addEdge(7, 5, "H <-> F", 10, 3F)
        graph.addEdge(0, 1, "A <-> B", 11, 3F)
        graph.addEdge(1, 2, "B <-> C", 12, 3F)
        graph.addEdge(2, 3, "C <-> D", 13, 3F)
        graph.addEdge(3, 4, "D <-> E", 14, 3F)
        graph.addEdge(2, 7, "C <-> H", 15, 3F)
        graph.addEdge(0, 5, "A <-> F", 16, 3F)

        val algoBridges = AlgoBridges(graph)
        algoBridges.findBridges()

        assertEquals(correctBridges.size, algoBridges.bridges.size)

        for (i in algoBridges.bridges) {
            assert(correctBridges.contains(i) || correctBridges.contains(Pair(i.second, i.first)))
        }
    }
}
